/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef USE_MOCK_JNI
#include "mock_jni.h"
#else
#include <jni.h>
#endif
/* Header for class org_llm_wrapper_LlamaCpp */

#ifndef _Included_org_llm_wrapper_LlamaCpp
#define _Included_org_llm_wrapper_LlamaCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_init
 * Signature: (Lorg/llm/wrapper/InitParams;)J
 */
JNIEXPORT jlong JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_generate
 * Signature: (JLorg/llm/wrapper/GenerateParams;)I
 */
JNIEXPORT jint JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1generate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_get_error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1get_1error
  (JNIEnv *, jclass);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_get_native_memory_usage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1get_1native_1memory_1usage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_get_os_memory_usage
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1get_1os_1memory_1usage
  (JNIEnv *, jclass);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_clear_chat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1clear_1chat
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
