/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_llm_wrapper_LlamaCpp */

#ifndef _Included_org_llm_wrapper_LlamaCpp
#define _Included_org_llm_wrapper_LlamaCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_init
 * Signature: (Lorg/llm/wrapper/InitParams;)J
 */
JNIEXPORT jlong JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1exit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_llm_wrapper_LlamaCpp
 * Method:    llama_generate
 * Signature: (JLorg/llm/wrapper/GenerateParams;)I
 */
JNIEXPORT jint JNICALL Java_org_llm_wrapper_LlamaCpp_llama_1generate
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
